### ISSUE TITLE
Encountering multiple issues with installation

### ISSUE THREAD

**Issue by AliceLoeser** [Netflix/dispatch-docker#2]
Hello,

Thanks for Dispatch, seems really cool. I can't wait to try it out for my company.
I am however encountering a bunch of different issues that prevent me from installing it on my machine, that I will list a bit bluntly.

- "_To get started with all the defaults, simply clone the repo and run `./docker/install.sh` in your local check-out. => the file is not located in /docker._" I guess it is refering to `./install.sh`?
- There is no Dockerfile
- I am using Docker version 18.09.2, build 6247962, and `docker build` must be called with an argument ("`docker build .`" would work).
- From looking at the installation script, I think a `dispatch` folder is missing?
- `SECRET_KEY=$(head /dev/urandom | tr -dc "a-z0-9@#%^&*(-_=+)" | head -c 50 | sed -e 's/[\/&]/\\&/g')` is not working on my mac, I guess it was made for linux? (tr: Illegal byte sequence) 

Again thanks a lot for the work, I might be able to fork it and work on the install script a little at the end of week.

Cheers

**Comment by AliceLoeser** [comment]
Seems related to #1

**Comment by kevgliss** [comment]
Would you mind trying again? I've merged in several fixes but would like to make sure that the issues you've run into were addressed.

**Comment by vramaiah** [comment]
With https://github.com/Netflix/dispatch/pull/53 most of the issues were resolved. The only thing I still receive is while setting up the database here - https://github.com/Netflix/dispatch-docker/blob/master/install.sh#L108-L112


Changing that from dispatch to postgres helps but leads to this new error - 
`/usr/local/bin/docker-entrypoint.sh: line 311: exec: database: not found`

**Comment by AliceLoeser** [comment]
Yes, I'm closing!
